<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MININT-MO2L6EH" ignored="0" tests="5" failures="1" timestamp="2020-06-22T23:56:08 EEST" time="0.008" errors="0">
  <testcase name="calculateTest2" time="0.002" classname="SimpleCalculateTests"/>
  <testcase name="calculateTest1" time="0.002" classname="SimpleCalculateTests"/>
  <testcase name="calculateTest4" time="0.001" classname="SimpleCalculateTests"/>
  <testcase name="calculateTest3" time="0.001" classname="SimpleCalculateTests">
    <failure type="java.lang.AssertionError" message="expected [8] but found [12]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [12]
at SimpleCalculateTests.calculateTest3(SimpleCalculateTests.java:30)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- calculateTest3 -->
  <testcase name="calculateTest5" time="0.0" classname="SimpleCalculateTests"/>
</testsuite>
